lzc-sdk-version: 0.1
name: lzc-nvc-test
package: ltp.lzcapp.nvc
version: 0.0.1
description:
license: https://choosealicense.com/licenses/mit/
homepage:
author:
application:
  subdomain: im
  routes:
    - /=http://imallinone.ltp.lzcapp.nvc.lzcapp:6901
  depends_on:
    - imallinone
  multi_instance: true # 是否启用多实例
  background_task: true #是否存在后台任务，若存在则系统不会对此app进行主动休眠等操作

services:
  imallinone:
    image: dev.longxiaoyi01.heiyu.space/lzc-vnc-test:0.0.2
    binds:
      - /lzcapp/run/home/:/home/lazycat/
    
